import os
from pathlib import Path

import wandb
import argparse
from tqdm import tqdm
from typing import Optional

import torch
import ultralytics

from models.yolo import YOLOModel
from utils.configv2 import YOLOConfig


class YOLOTrainer:
    def __init__(self, config: YOLOConfig):
        self.config = config
        self.device = torch.device(config.device)
        
        # Initialize model
        self.model = YOLOModel(config)
        
        # Training state
        self.current_epoch = 0
        self.best_map = 0.0
        
        # These will be set after training starts
        self.output_dir = None
        self.run_name = None
    
    def init_wandb(self, run_name: str):
        """Initialize Weights & Biases logging"""
        if self.config.wandb_mode != 'disabled':
            wandb.init(
                project=self.config.wandb_project,
                name=f"{self.config.wandb_name}_{run_name}",
                config=self.config.__dict__,
                mode=self.config.wandb_mode
            )
        print(f"Wandb mode: {self.config.wandb_mode}")
    
    
    def train(self):
        """Train the YOLO model"""
        print(f"Starting YOLO training for {self.config.epochs} epochs")
        
        # Let YOLO handle directory creation
        results = self.model.train(
            project=self.config.output_path,
            name=self.config.project_name,
        )
        
        # Get the actual output directory that YOLO created
        # YOLO creates: runs/{project_name}/{run_name}
        self.run_name = results.save_dir.name
        self.output_dir = "%s/%s/%s" % (
            self.config.output_path, self.config.project_name, self.run_name
        )
        
        print(f"YOLO created output directory: {self.output_dir}")
        
        # Initialize wandb with the actual run name
        self.init_wandb(self.run_name)
        
        # Get training results and log to wandb
        if self.config.wandb_mode != 'disabled':
            self.log_results(results)
        
        print("Training completed!")
        return results
    
    def log_results(self, results):
        """Log training results to wandb"""
        if hasattr(results, 'results_dict'):
            wandb.log(results.results_dict)
        
        # Log any CSV files generated by YOLO
        csv_files = list(self.output_dir.glob('*.csv'))
        for csv_file in csv_files:
            wandb.save(str(csv_file))
    
    def validate(self, model_path: Optional[str] = None):
        """Validate the trained model"""
        if model_path:
            # Load specific model for validation
            temp_config = self.config
            temp_config.checkpoint_path = model_path
            model = YOLOModel(temp_config)
        else:
            model = self.model
        
        print("Running validation...")
        results = model.validate()
        
        if self.config.wandb_mode != 'disabled':
            wandb.log({"val_map": results.box.map})
        
        return results
    
    def test_predictions(self, test_images_path: str, output_path: Optional[str] = None):
        """Test the model on sample images"""
        if output_path is None:
            output_path = "%s/test_predictions" % self.output_dir
        
        output_path = Path(output_path)
        output_path.mkdir(parents=True, exist_ok=True)
        
        test_images = list(Path(test_images_path).glob('*.png')) + \
                     list(Path(test_images_path).glob('*.jpg')) + \
                     list(Path(test_images_path).glob('*.jpeg'))
        
        print(f"Testing on {len(test_images)} images...")
        
        for image_path in tqdm(test_images, desc="Testing"):
            results = self.model.predict(str(image_path))
            
            # Save prediction
            if results and len(results) > 0:
                result = results[0]
                result.save(filename=str("%s/%s" % (output_path, f"pred_{image_path.name}")))
                
                # Log detection info
                if len(result.boxes) > 0:
                    for i, box in enumerate(result.boxes):
                        conf = box.conf.item() if hasattr(box.conf, 'item') else box.conf
                        print(f"  {image_path.name}: Detection {i+1} - Confidence: {conf:.4f}")
                else:
                    print(f"  {image_path.name}: No detections")
        
        print(f"Test predictions saved to: {output_path}")


def parse_args():
    parser = argparse.ArgumentParser(description="YOLO training config")

    parser.add_argument(
        "--dataset_path",
        type=str,
        default=YOLOConfig.dataset_path,
        help="Path to training dataset",
    )
    parser.add_argument(
        "--val_dataset_path",
        type=str,
        default=YOLOConfig.val_dataset_path,
        help="Path to validation dataset",
    )
    parser.add_argument(
        "--model_type",
        type=str,
        default=YOLOConfig.model_type,
        help="Path to pretrained checkpoint",
    )
    parser.add_argument(
        "--pretrained_path",
        type=str,
        default=YOLOConfig.pretrained_path,
        help="Path to pretrained checkpoint",
    )
    parser.add_argument(
        "--output_path",
        type=str,
        default=YOLOConfig.output_path,
        help="Path to training checkpoint",
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=YOLOConfig.learning_rate,
        help="Learning rate",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=YOLOConfig.batch_size,
    )
    parser.add_argument(
        "--image_size",
        type=int,
        default=640, # 960, 1024
    )

    return parser.parse_args()


def main():
    """Main training function"""
    # Configuration
    args = parse_args()

    config = YOLOConfig(
        # Model settings
        model_type=args.model_type,
        pretrained_path=args.pretrained_path,
        device="cuda",
        output_path=args.output_path,
        
        # Dataset paths
        dataset_path=args.dataset_path,
        val_dataset_path=args.val_dataset_path,
        class_names=['pl'],
        
        # Training parameters
        epochs=300,
        batch_size=args.batch_size,
        image_size=args.image_size, # 960, 1024
        patience=50,
        
        # Augmentation (optimized for medical scars)
        mosaic=0.,      # or 0.0 if anatomy becomes unrealistic
        mixup=0,        # often not ideal for medical lesion detection
        copy_paste=0.,   # only if masks/boxes are accurate and pasted lesions stay realistic
        degrees=5.0,      # reduce geometric distortion
        flipud=0.0,       # usually avoid unless anatomically valid
        fliplr=0.5,       # acceptable in many whole-body setups, task-dependent
        hsv_h=0.0,
        hsv_s=0.0,
        hsv_v=0.0,
        translate=0.05,
        scale=0.05,
        erasing=0.0,
        
        # Detection parameters
        iou_threshold=0.2,
        conf_threshold=0.05,
        max_detections=30,

        # Training settings
        multi_scale=False,
        test_time_augmentation=False,
        save_period=50,
    
        # Optimizer parameters
        learning_rate=args.learning_rate,
        
        # Project settings
        project_name="yolo_pl_detection_lr%f" % args.learning_rate,
        experiment_name="enhanced_pl_detection_lr%f" % args.learning_rate,
        
        # Wandb settings
        wandb_project="YOLO-pl-detection",
        wandb_name="pl_detection_v1",
        wandb_mode="disabled"  # Set to "online" to enable wandb logging
    )

    ultralytics.settings.update({
        "runs_dir": config.output_path,
    })
    
    # Create trainer
    trainer = YOLOTrainer(config)
    
    # Train the model
    results = trainer.train()
    
    # Validate the model
    val_results = trainer.validate()
    print(f"Validation mAP: {val_results.box.map:.4f}")
    
    # Test on sample images (optional)
    # trainer.test_predictions("/path/to/test/images")
    
    print("Training pipeline completed!")


if __name__ == "__main__":
    main() 